### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by yan97ao** [ether/etherpad-docker#8]
# docker pull leibnitius/etherpad-docker
Using default tag: latest
Trying to pull repository docker.io/leibnitius/etherpad-docker ... 
Pulling repository docker.io/leibnitius/etherpad-docker
Error: image leibnitius/etherpad-docker:latest not found

**Comment by muxator** [comment]
That's true.
The image does not seem to be maintained anymore. Probably we should offer an official one, or not mention it at all.

You can still build the image by yourself, if you see fit (taken from [README.md](https://github.com/ether/etherpad-docker/blob/master/README.md)):


```
git clone git://github.com/ether/etherpad-docker.git && cd etherpad-docker
```

Then edit the settings.json to your liking and run:

```
docker build -t <YOUR_USERNAME>/etherpad-docker .
```

**Comment by nashe** [comment]
@lpagliari: does the Etherpad foundation own https://hub.docker.com/r/etherpad/ or https://hub.docker.com/r/ether/? It would be nice to have an official image!

**Comment by Trolldemorted** [comment]
Are there any updates on this?

An official image would be awesome, and I think they can be run automatically.

**Comment by lpagliari** [comment]
@nashe Hum, I don't know, good question. Maybe @JohnMcLear knows something about this?

**Comment by Trolldemorted** [comment]
FYI, you might want to [give docker's automatic builds for github a try](https://docs.docker.com/docker-hub/github/). I really would like to pull in an official image instead of building it myself or rely on third parties.

**Comment by JohnMcLear** [comment]
Sorry no

JOHN MCLEAR
CTO



Unit 2A, Prospect Works, Bradford, BD15 7AF

www.mclear.com<http://www.mclear.com/>



Privileged, Secret, Proprietary & Confidential

For internal communications related to legal affairs, this email contains information that is attorney client privileged. This electronic message transmission contains information which is proprietary, confidential, and privileged. The information is intended solely for the intended recipient, and use by any other party is not authorized. The unauthorized disclosure or interception of email is a federal crime. 18 U.S.C. Sec. 2511(4).

________________________________

**Comment by muxator** [comment]
So we do not know who owns https://hub.docker.com/r/ether/ and https://hub.docker.com/r/etherpad/ ?

**Comment by muxator** [comment]
Thanks @JohnMcLear, account taken.

We can start thinking about how to have an official Docker image in good shape.
Leaving the ticket open for now, until something is published.

**Comment by muxator** [comment]
Published the [current development version](https://github.com/ether/etherpad-lite/tree/49449453c9b268495663127b17c7a659ad4f3cf9) at https://hub.docker.com/r/etherpad/etherpad/

Probably we should publish stable versions with explicit tags, and the development version with `:latest`.
